### PR TITLE
Ninja as a dependency in JIT mode

### PR DESCRIPTION
**Pull request by ur4t**

### CODE REVIEW

**Review by yzh119 — COMMENTED** [review]
Sorry I'm a little bit confused, can you clarify what need to be specified as `requires` in `_get_requires_for_build` function and what need to be set as `install_requires`? Thanks!

**Comment by ur4t** [comment]
> Sorry I'm a little bit confused, can you clarify what need to be specified as `requires` in `_get_requires_for_build` function and what need to be set as `install_requires`? Thanks!

@yzh119 Sorry for insufficient description.

`install_requires` in `setup.py` and `project.dependencies` in `pyproject.toml` specifies packages required at runtime.
`build-system.requires` in `pyproject.toml` specifies packages required to build the package, and
`_get_requires_for_build` can specifies addtional packages considering options like `FLASHINFER_ENABLE_AOT=1`.

In JIT mode, we do not build shared objects when building the package, but users need `ninja` to accelerate building. Thus `ninja` should be in `install_requires`/`project.dependencies`. It is ok that `_get_requires_for_build` specifies `ninja` but not necessary.

In AOT mode it is just opposite. `ninja` is supposed to be present in `_get_requires_for_build` and absent in `install_requires`/`project.dependencies`.

**Comment by zhyncs** [comment]
Hi @ur4t It seems that the latest main `FLASHINFER_BUILD_VERSION` isn't working.

**Comment by zhyncs** [comment]
ref https://github.com/flashinfer-ai/flashinfer-nightly/blob/2b994bf8560bc07130533bfb4f4895e86c2f81f8/.github/workflows/nightly-release.yml#L53-L64C18

**Pull request merged**
