### PR TITLE
[CMake] Add positional independent code (PIC) option to kernels

### PR DESCRIPTION
**Pull request by MasterJH5574**
This PR adds the `-fPIC` option to prefill/decode kernels for packaging.

### CODE REVIEW

**Comment by MasterJH5574** [comment]
Pending for validation. Marked as draft for now.

**Comment by yzh119** [comment]
@MasterJH5574 Does this solution work?

**Comment by MasterJH5574** [comment]
@yzh119 yes it addresses the PIC issue. But still another commit is needed to fix some other issues.

**Review by yzh119 — APPROVED** [review]
LGTM, thank you @MasterJH5574 !

**Pull request merged**
