### PR TITLE
feat: support fused add rmsnorm

### PR DESCRIPTION
**Pull request by zhyncs**
ref https://github.com/sgl-project/sglang/pull/907 cc @yzh119

### CODE REVIEW

**Comment by yzh119** [comment]
Can you write a test for this function?

**Comment by zhyncs** [comment]
> Can you write a test for this function?

OK

**Comment by zhyncs** [comment]
Hi @yzh119 I have added unit tests to that PR in SGLang, and the verification shows no issues. I need to figure out how to proceed with FlashInfer.
https://github.com/sgl-project/sglang/pull/907/files#diff-ffbd8966453a6660e47ec2a8b0f5a71fee45b9e0fd729577ef28cfb60d3ee774
```
python3 python/sglang/test/test_layernorm.py

test_rms_norm (__main__.TestRMSNorm.test_rms_norm) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.608s

OK
```

**Comment by yzh119** [comment]
I think adding a test case in https://github.com/flashinfer-ai/flashinfer/blob/main/python/tests/test_norm.py would be great.

**Comment by zhyncs** [comment]
> I think adding a test case in https://github.com/flashinfer-ai/flashinfer/blob/main/python/tests/test_norm.py would be great.

sure!

**Comment by zhyncs** [comment]
> I think adding a test case in https://github.com/flashinfer-ai/flashinfer/blob/main/python/tests/test_norm.py would be great.

@yzh119 done.

```bash
pytest python/tests/test_norm.py
```

```
=================================================================================== test session starts ===================================================================================
platform linux -- Python 3.11.5, pytest-8.3.2, pluggy-1.5.0
rootdir: /root/flashinfer/python
plugins: anyio-4.4.0
collected 48 items

python/tests/test_norm.py ................................................                                                                                                          [100%]

=================================================================================== 48 passed in 6.86s ====================================================================================
```

**Review by yzh119 — APPROVED** [review]
LGTM, thank you @zhyncs !

**Pull request merged**
