### PR TITLE
bugfix: Fix sm75 kernel configuration

### PR DESCRIPTION
**Pull request by yzh119**
Some kernel configurations are not compatible with sm75, this pr fix these issues.

### CODE REVIEW

**Comment by zhyncs** [comment]
Ok I will verify it locally asap.

**Review by zhyncs — APPROVED** [review]
LGTM. It works when
```bash
python3 -m sglang.launch_server --model Qwen/Qwen1.5-1.8B-Chat --dtype float16 --disable-flashinfer-sampling --disable-cuda-graph
```

**Comment by yzh119** [comment]
why disable sampling and cudagraph?

**Comment by zhyncs** [comment]
> why disable sampling and cudagraph?

CUDA Graph doesn't work with Google Colab's T4 but works with GCP's T4, which is confusing. Also, Sampling doesn't work on sm75.
```
RuntimeError: TopKRenormProb failed with error code invalid device function
```

**Comment by yzh119** [comment]
> Sampling doesn't work on sm75.

I should fix this.

**Comment by zhyncs** [comment]
I reviewed the code and it should be compatible with sm75. I am going to extract this kernel and validate it on T4 separately.

**Comment by zhyncs** [comment]
Maybe we don't need to modify the const expr part subsequently, and choose to add `--expt-relaxed-constexpr` in the compilation parameters instead.

**Comment by zhyncs** [comment]
> CUDA Graph doesn't work with Google Colab's T4 but works with GCP's T4, which is confusing.

I figured it out. This is because `mem-frac` was set when running on GCP T4, so actually CUDA Graph can be enabled. Since the VRAM of T4 is relatively **small**, the default `mem-frac` will prevent CUDA Graph from being enabled. This has nothing to do with FlashInfer. Cheers.

**Comment by yzh119** [comment]
> Maybe we don't need to modify the const expr part subsequently, and choose to add `--expt-relaxed-constexpr` in the compilation parameters instead.

The main issue is `__CUDA_ARCH__` only works in device functions (inside kernels), and we can't rely on them in host functions.

**Comment by zhyncs** [comment]
Nice work! I will integrate it into SGLang.

**Pull request merged**
